### PR TITLE
Finished promise

### PR DESCRIPTION
**Pull request by c19**
finished function return a promise instead of using a callback.

### CODE REVIEW

**Comment by sainthkh** [comment]
This PR would break current API, wouldn't it?

**Comment by c19** [comment]
> This PR would break current API, wouldn't it?

Yes, we could add another API to satisfy different style of async code and keep backward compatible. I'll leave that for you decide.

**Comment by sainthkh** [comment]
To make current API valid, how about renaming suggested promise versions to `finishedP` and `finishedWithErrorP` and not making changes to current `finished` functions.

**Comment by c19** [comment]
updated.

**Pull request merged**
